"""LexMind Artifact Management System.

Tracks every output generated by the processing pipeline:
OCR, parsed text, embeddings, graphs, timelines, reports, exports.

No producers.  No storage implementation.
Only the artifact framework.
"""

from lexmind.artifacts.artifact import Artifact
from lexmind.artifacts.artifact_dependency import (
    ArtifactDependency,
    DependencyGraph,
)
from lexmind.artifacts.artifact_events import (
    ArtifactArchived,
    ArtifactCreated,
    ArtifactDeleted,
    ArtifactSuperseded,
    ArtifactValidated,
)
from lexmind.artifacts.artifact_exceptions import (
    ArtifactAlreadyExistsError,
    ArtifactChecksumError,
    ArtifactDependencyError,
    ArtifactError,
    ArtifactNotFoundError,
    ArtifactStateError,
    ArtifactValidationError,
    ArtifactVersionError,
)
from lexmind.artifacts.artifact_lineage import LineageStep, LineageTracker
from lexmind.artifacts.artifact_manager import ArtifactManager
from lexmind.artifacts.artifact_manifest import (
    ArtifactManifest,
    ArtifactManifestValidator,
    ManifestValidationResult,
)
from lexmind.artifacts.artifact_metadata import ArtifactMetadata
from lexmind.artifacts.artifact_registry import ArtifactRegistry
from lexmind.artifacts.artifact_state import (
    VALID_ARTIFACT_TRANSITIONS,
    ArtifactStatus,
    can_transition_artifact,
)
from lexmind.artifacts.artifact_types import PIPELINE_ORDER, ArtifactType
from lexmind.artifacts.artifact_version import ArtifactVersion

__all__ = [
    "Artifact",
    "ArtifactArchived",
    "ArtifactAlreadyExistsError",
    "ArtifactChecksumError",
    "ArtifactCreated",
    "ArtifactDeleted",
    "ArtifactDependency",
    "ArtifactDependencyError",
    "ArtifactError",
    "ArtifactManifest",
    "ArtifactManifestValidator",
    "ArtifactManager",
    "ArtifactMetadata",
    "ArtifactNotFoundError",
    "ArtifactRegistry",
    "ArtifactStateError",
    "ArtifactStatus",
    "ArtifactSuperseded",
    "ArtifactType",
    "ArtifactValidationError",
    "ArtifactValidated",
    "ArtifactVersion",
    "ArtifactVersionError",
    "DependencyGraph",
    "LineageStep",
    "LineageTracker",
    "ManifestValidationResult",
    "PIPELINE_ORDER",
    "VALID_ARTIFACT_TRANSITIONS",
    "can_transition_artifact",
]
